/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-postgres'
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  numeric,
  jsonb,
  boolean,
  pgEnum,
} from '@payloadcms/db-postgres/drizzle/pg-core'
import { sql, relations } from '@payloadcms/db-postgres/drizzle'
export const enum_blogs_status = pgEnum('enum_blogs_status', ['draft', 'published'])
export const enum__blogs_v_version_status = pgEnum('enum__blogs_v_version_status', [
  'draft',
  'published',
])
export const enum_payload_jobs_log_task_slug = pgEnum('enum_payload_jobs_log_task_slug', [
  'inline',
  'schedulePublish',
])
export const enum_payload_jobs_log_state = pgEnum('enum_payload_jobs_log_state', [
  'failed',
  'succeeded',
])
export const enum_payload_jobs_task_slug = pgEnum('enum_payload_jobs_task_slug', [
  'inline',
  'schedulePublish',
])

export const users_sessions = pgTable(
  'users_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
    expiresAt: timestamp('expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index('users_sessions_order_idx').on(columns._order),
    index('users_sessions_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const users = pgTable(
  'users',
  {
    id: serial('id').primaryKey(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    email: varchar('email').notNull(),
    resetPasswordToken: varchar('reset_password_token'),
    resetPasswordExpiration: timestamp('reset_password_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar('salt'),
    hash: varchar('hash'),
    loginAttempts: numeric('login_attempts', { mode: 'number' }).default(0),
    lockUntil: timestamp('lock_until', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => [
    index('users_updated_at_idx').on(columns.updatedAt),
    index('users_created_at_idx').on(columns.createdAt),
    uniqueIndex('users_email_idx').on(columns.email),
  ],
)

export const media = pgTable(
  'media',
  {
    id: serial('id').primaryKey(),
    alt: varchar('alt').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
  },
  (columns) => [
    index('media_updated_at_idx').on(columns.updatedAt),
    index('media_created_at_idx').on(columns.createdAt),
    uniqueIndex('media_filename_idx').on(columns.filename),
  ],
)

export const blogs = pgTable(
  'blogs',
  {
    id: serial('id').primaryKey(),
    title: varchar('title'),
    content: jsonb('content'),
    author: integer('author_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    authorSocialLinks_twitter: varchar('author_social_links_twitter'),
    authorSocialLinks_linkedin: varchar('author_social_links_linkedin'),
    authorSocialLinks_github: varchar('author_social_links_github'),
    authorSocialLinks_website: varchar('author_social_links_website'),
    generateSlug: boolean('generate_slug').default(true),
    slug: varchar('slug'),
    bannerImage: integer('banner_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    thumbnailImage: integer('thumbnail_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    publishDate: timestamp('publish_date', { mode: 'string', withTimezone: true, precision: 3 }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    _status: enum_blogs_status('_status').default('draft'),
  },
  (columns) => [
    index('blogs_author_idx').on(columns.author),
    uniqueIndex('blogs_slug_idx').on(columns.slug),
    index('blogs_banner_image_idx').on(columns.bannerImage),
    index('blogs_thumbnail_image_idx').on(columns.thumbnailImage),
    index('blogs_updated_at_idx').on(columns.updatedAt),
    index('blogs_created_at_idx').on(columns.createdAt),
    index('blogs__status_idx').on(columns._status),
  ],
)

export const _blogs_v = pgTable(
  '_blogs_v',
  {
    id: serial('id').primaryKey(),
    parent: integer('parent_id').references(() => blogs.id, {
      onDelete: 'set null',
    }),
    version_title: varchar('version_title'),
    version_content: jsonb('version_content'),
    version_author: integer('version_author_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    version_authorSocialLinks_twitter: varchar('version_author_social_links_twitter'),
    version_authorSocialLinks_linkedin: varchar('version_author_social_links_linkedin'),
    version_authorSocialLinks_github: varchar('version_author_social_links_github'),
    version_authorSocialLinks_website: varchar('version_author_social_links_website'),
    version_generateSlug: boolean('version_generate_slug').default(true),
    version_slug: varchar('version_slug'),
    version_bannerImage: integer('version_banner_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    version_thumbnailImage: integer('version_thumbnail_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    version_publishDate: timestamp('version_publish_date', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_updatedAt: timestamp('version_updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp('version_created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version__status: enum__blogs_v_version_status('version__status').default('draft'),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    latest: boolean('latest'),
    autosave: boolean('autosave'),
  },
  (columns) => [
    index('_blogs_v_parent_idx').on(columns.parent),
    index('_blogs_v_version_version_author_idx').on(columns.version_author),
    index('_blogs_v_version_version_slug_idx').on(columns.version_slug),
    index('_blogs_v_version_version_banner_image_idx').on(columns.version_bannerImage),
    index('_blogs_v_version_version_thumbnail_image_idx').on(columns.version_thumbnailImage),
    index('_blogs_v_version_version_updated_at_idx').on(columns.version_updatedAt),
    index('_blogs_v_version_version_created_at_idx').on(columns.version_createdAt),
    index('_blogs_v_version_version__status_idx').on(columns.version__status),
    index('_blogs_v_created_at_idx').on(columns.createdAt),
    index('_blogs_v_updated_at_idx').on(columns.updatedAt),
    index('_blogs_v_latest_idx').on(columns.latest),
    index('_blogs_v_autosave_idx').on(columns.autosave),
  ],
)

export const blog_embeddings = pgTable(
  'blog_embeddings',
  {
    id: serial('id').primaryKey(),
    blog: integer('blog_id')
      .notNull()
      .references(() => blogs.id, {
        onDelete: 'set null',
      }),
    chunkIndex: numeric('chunk_index', { mode: 'number' }).notNull(),
    content: varchar('content').notNull(),
    embedding: jsonb('embedding').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('blog_embeddings_blog_idx').on(columns.blog),
    index('blog_embeddings_updated_at_idx').on(columns.updatedAt),
    index('blog_embeddings_created_at_idx').on(columns.createdAt),
    index('blog_idx').on(columns.blog),
    uniqueIndex('blog_chunkIndex_idx').on(columns.blog, columns.chunkIndex),
  ],
)

export const payload_kv = pgTable(
  'payload_kv',
  {
    id: serial('id').primaryKey(),
    key: varchar('key').notNull(),
    data: jsonb('data').notNull(),
  },
  (columns) => [uniqueIndex('payload_kv_key_idx').on(columns.key)],
)

export const payload_jobs_log = pgTable(
  'payload_jobs_log',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    executedAt: timestamp('executed_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
    completedAt: timestamp('completed_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
    taskSlug: enum_payload_jobs_log_task_slug('task_slug').notNull(),
    taskID: varchar('task_i_d').notNull(),
    input: jsonb('input'),
    output: jsonb('output'),
    state: enum_payload_jobs_log_state('state').notNull(),
    error: jsonb('error'),
  },
  (columns) => [
    index('payload_jobs_log_order_idx').on(columns._order),
    index('payload_jobs_log_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [payload_jobs.id],
      name: 'payload_jobs_log_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_jobs = pgTable(
  'payload_jobs',
  {
    id: serial('id').primaryKey(),
    input: jsonb('input'),
    completedAt: timestamp('completed_at', { mode: 'string', withTimezone: true, precision: 3 }),
    totalTried: numeric('total_tried', { mode: 'number' }).default(0),
    hasError: boolean('has_error').default(false),
    error: jsonb('error'),
    taskSlug: enum_payload_jobs_task_slug('task_slug'),
    queue: varchar('queue').default('default'),
    waitUntil: timestamp('wait_until', { mode: 'string', withTimezone: true, precision: 3 }),
    processing: boolean('processing').default(false),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_jobs_completed_at_idx').on(columns.completedAt),
    index('payload_jobs_total_tried_idx').on(columns.totalTried),
    index('payload_jobs_has_error_idx').on(columns.hasError),
    index('payload_jobs_task_slug_idx').on(columns.taskSlug),
    index('payload_jobs_queue_idx').on(columns.queue),
    index('payload_jobs_wait_until_idx').on(columns.waitUntil),
    index('payload_jobs_processing_idx').on(columns.processing),
    index('payload_jobs_updated_at_idx').on(columns.updatedAt),
    index('payload_jobs_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents = pgTable(
  'payload_locked_documents',
  {
    id: serial('id').primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
    index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
    index('payload_locked_documents_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents_rels = pgTable(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
    mediaID: integer('media_id'),
    blogsID: integer('blogs_id'),
    'blog-embeddingsID': integer('blog_embeddings_id'),
    'payload-kvID': integer('payload_kv_id'),
    'payload-jobsID': integer('payload_jobs_id'),
  },
  (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order),
    index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    index('payload_locked_documents_rels_path_idx').on(columns.path),
    index('payload_locked_documents_rels_users_id_idx').on(columns.usersID),
    index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID),
    index('payload_locked_documents_rels_blogs_id_idx').on(columns.blogsID),
    index('payload_locked_documents_rels_blog_embeddings_id_idx').on(columns['blog-embeddingsID']),
    index('payload_locked_documents_rels_payload_kv_id_idx').on(columns['payload-kvID']),
    index('payload_locked_documents_rels_payload_jobs_id_idx').on(columns['payload-jobsID']),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['blogsID']],
      foreignColumns: [blogs.id],
      name: 'payload_locked_documents_rels_blogs_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['blog-embeddingsID']],
      foreignColumns: [blog_embeddings.id],
      name: 'payload_locked_documents_rels_blog_embeddings_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['payload-kvID']],
      foreignColumns: [payload_kv.id],
      name: 'payload_locked_documents_rels_payload_kv_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['payload-jobsID']],
      foreignColumns: [payload_jobs.id],
      name: 'payload_locked_documents_rels_payload_jobs_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_preferences = pgTable(
  'payload_preferences',
  {
    id: serial('id').primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_preferences_key_idx').on(columns.key),
    index('payload_preferences_updated_at_idx').on(columns.updatedAt),
    index('payload_preferences_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_preferences_rels = pgTable(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order),
    index('payload_preferences_rels_parent_idx').on(columns.parent),
    index('payload_preferences_rels_path_idx').on(columns.path),
    index('payload_preferences_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_migrations = pgTable(
  'payload_migrations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    batch: numeric('batch', { mode: 'number' }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt),
    index('payload_migrations_created_at_idx').on(columns.createdAt),
  ],
)

export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
  }),
}))
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: 'sessions',
  }),
}))
export const relations_media = relations(media, () => ({}))
export const relations_blogs = relations(blogs, ({ one }) => ({
  author: one(users, {
    fields: [blogs.author],
    references: [users.id],
    relationName: 'author',
  }),
  bannerImage: one(media, {
    fields: [blogs.bannerImage],
    references: [media.id],
    relationName: 'bannerImage',
  }),
  thumbnailImage: one(media, {
    fields: [blogs.thumbnailImage],
    references: [media.id],
    relationName: 'thumbnailImage',
  }),
}))
export const relations__blogs_v = relations(_blogs_v, ({ one }) => ({
  parent: one(blogs, {
    fields: [_blogs_v.parent],
    references: [blogs.id],
    relationName: 'parent',
  }),
  version_author: one(users, {
    fields: [_blogs_v.version_author],
    references: [users.id],
    relationName: 'version_author',
  }),
  version_bannerImage: one(media, {
    fields: [_blogs_v.version_bannerImage],
    references: [media.id],
    relationName: 'version_bannerImage',
  }),
  version_thumbnailImage: one(media, {
    fields: [_blogs_v.version_thumbnailImage],
    references: [media.id],
    relationName: 'version_thumbnailImage',
  }),
}))
export const relations_blog_embeddings = relations(blog_embeddings, ({ one }) => ({
  blog: one(blogs, {
    fields: [blog_embeddings.blog],
    references: [blogs.id],
    relationName: 'blog',
  }),
}))
export const relations_payload_kv = relations(payload_kv, () => ({}))
export const relations_payload_jobs_log = relations(payload_jobs_log, ({ one }) => ({
  _parentID: one(payload_jobs, {
    fields: [payload_jobs_log._parentID],
    references: [payload_jobs.id],
    relationName: 'log',
  }),
}))
export const relations_payload_jobs = relations(payload_jobs, ({ many }) => ({
  log: many(payload_jobs_log, {
    relationName: 'log',
  }),
}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
    blogsID: one(blogs, {
      fields: [payload_locked_documents_rels.blogsID],
      references: [blogs.id],
      relationName: 'blogs',
    }),
    'blog-embeddingsID': one(blog_embeddings, {
      fields: [payload_locked_documents_rels['blog-embeddingsID']],
      references: [blog_embeddings.id],
      relationName: 'blog-embeddings',
    }),
    'payload-kvID': one(payload_kv, {
      fields: [payload_locked_documents_rels['payload-kvID']],
      references: [payload_kv.id],
      relationName: 'payload-kv',
    }),
    'payload-jobsID': one(payload_jobs, {
      fields: [payload_locked_documents_rels['payload-jobsID']],
      references: [payload_jobs.id],
      relationName: 'payload-jobs',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))

type DatabaseSchema = {
  enum_blogs_status: typeof enum_blogs_status
  enum__blogs_v_version_status: typeof enum__blogs_v_version_status
  enum_payload_jobs_log_task_slug: typeof enum_payload_jobs_log_task_slug
  enum_payload_jobs_log_state: typeof enum_payload_jobs_log_state
  enum_payload_jobs_task_slug: typeof enum_payload_jobs_task_slug
  users_sessions: typeof users_sessions
  users: typeof users
  media: typeof media
  blogs: typeof blogs
  _blogs_v: typeof _blogs_v
  blog_embeddings: typeof blog_embeddings
  payload_kv: typeof payload_kv
  payload_jobs_log: typeof payload_jobs_log
  payload_jobs: typeof payload_jobs
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  relations_users_sessions: typeof relations_users_sessions
  relations_users: typeof relations_users
  relations_media: typeof relations_media
  relations_blogs: typeof relations_blogs
  relations__blogs_v: typeof relations__blogs_v
  relations_blog_embeddings: typeof relations_blog_embeddings
  relations_payload_kv: typeof relations_payload_kv
  relations_payload_jobs_log: typeof relations_payload_jobs_log
  relations_payload_jobs: typeof relations_payload_jobs
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
}

declare module '@payloadcms/db-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
